version: '3.8'

services:
  # Angular frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - devops-app-1  # Assuming this is the name of your Spring Boot service in the backend Docker Compose file
