version: '3.8'

services:
  # Angular frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - my_network
networks:
  my_network:
    external: true
