version: '3.8'

services:
  # MySQL database service
  mysql-youssef:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: devops
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my_network

  # Spring Boot application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mysql-youssef
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-youssef:3306/devops?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root_password
    networks:
      - my_network

volumes:
  mysql-data:

networks:
  my_network:
    external: true
